giftcardreaderfix: giftcardreaderfixed.c
	gcc -o giftcardreaderfixed giftcardreaderfixed.c && ./giftcardreaderfixed 1 examplefile.gft


giftcardexamplewriter:
	gcc -o giftcardexamplewriter giftcardexamplewriter.c && ./giftcardexamplewriter


