name: learn-github-actions

on: [push]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: "Hang File Crash"
      run: ./giftcardreaderfixed 1 ./part2/tests/hang.gft
    - name: "Crash 1 file"
      run: ./giftcardreaderfixed 1 ./part2/tests/crash1.gft
    - name: "Crash 2 empty argument"
      run: ./giftcardreaderfixed 1 
    - name: "coverage increase 1"
      run: ./giftcardreaderfixed 1 ./part3/fuzz/cov1.gft
    - name: "coverge increase 2"
      run: ./giftcardreaderfixed 1 ./part3/fuzz/cov2.gft
    - name: "fuzzer 1 case"
      run: ./giftcardreaderfixed 1 ./part3/fuzz/fuzzer1.gft
    - name: "fuzzer 2 case"
      run: ./giftcardreaderfixed 1 ./part3/fuzz/fuzzer2.gft
